[project]
name = "backend"
version = "0.1.0"
description = "This is for backend services"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.30",
    "fastapi>=0.128.0",
    "mangum>=0.20.0",
    "uvicorn>=0.40.0",
]
